<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Product viewed counter template
 *
 * @var $block \Vkr\Kalman\Block\Ui\ProductViewCounter
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
                "Vkr_Kalman/js/product/view/provider": {
                    "data": <?= /* @noEscape */ $block->getCurrentProductData() ?>
            }
        }
    }
</script>
